version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_ROOT}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_DB}
    ports:
      - 3306:3306
    restart: always

  app:
    container_name: app
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_USER: ${MYSQL_DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      # MYSQL_DATABASE_USER: root
      # MYSQL_DATABASE_PASSWORD: ${MYSQL_DATABASE_ROOT}
      MYSQL_DATABASE_DB: ${MYSQL_DATABASE_DB}
      SECRET_KEY: ${SECRET_KEY}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:5000

volumes:
  mysql: